# Generated by Django 5.2.17 on 2026-09-19 17:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('funder', models.CharField(default='SEDFA', max_length=120)),
                ('fy_start_year', models.PositiveIntegerField(help_text='2026 means FY 2026/27')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'ordering': ['-fy_start_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Registered name')),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='CIPC registration no.')),
                ('sector', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('electronics', 'Electronics & devices'), ('agro', 'Agro-processing'), ('construction', 'Construction'), ('ict', 'ICT & digital'), ('services', 'Services'), ('retail', 'Retail & trade'), ('energy', 'Energy'), ('other', 'Other')], max_length=20)),
                ('province', models.CharField(choices=[('NW', 'North West'), ('GP', 'Gauteng'), ('NC', 'Northern Cape'), ('OT', 'Other')], max_length=2)),
                ('town', models.CharField(max_length=120, verbose_name='Town or township')),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('description', models.TextField(verbose_name='What the business does')),
                ('bbbee_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='B-BBEE level')),
                ('black_owned_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Black-owned %')),
                ('women_owned_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Women-owned %')),
                ('youth_owned_pct', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Youth-owned %')),
                ('employees_at_intake', models.PositiveIntegerField(default=0)),
                ('annual_turnover_at_intake', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('learnable_enrolled', models.BooleanField(default=False, verbose_name='Enrolled on Learnable')),
                ('stage', models.CharField(choices=[('applicant', 'Applicant'), ('screening', 'Screening'), ('onboarded', 'Onboarded'), ('incubating', 'Incubating'), ('graduated', 'Graduated'), ('exited', 'Exited'), ('declined', 'Declined')], default='applicant', editable=False, max_length=12)),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='incubator.cohort')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('assessor', models.CharField(max_length=120)),
                ('finance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('marketing', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('operations', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('compliance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('people', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('digital', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='incubator.enterprise')),
            ],
            options={
                'ordering': ['-assessed_on'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mentoring', 'Mentoring'), ('training', 'Training'), ('bds', 'Business development service'), ('market', 'Market access'), ('finance', 'Finance linkage'), ('compliance', 'Compliance support'), ('facility', 'Equipment or workspace')], max_length=12)),
                ('delivered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('provider', models.CharField(max_length=160)),
                ('hours', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('summary', models.TextField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='incubator.enterprise')),
            ],
            options={
                'ordering': ['-delivered_on'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('done', 'Done'), ('missed', 'Missed')], default='planned', max_length=12)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='incubator.enterprise')),
            ],
            options={
                'ordering': ['due_on'],
            },
        ),
        migrations.AddField(
            model_name='cohort',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='incubator.programme'),
        ),
        migrations.CreateModel(
            name='StageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('applicant', 'Applicant'), ('screening', 'Screening'), ('onboarded', 'Onboarded'), ('incubating', 'Incubating'), ('graduated', 'Graduated'), ('exited', 'Exited'), ('declined', 'Declined')], max_length=12)),
                ('to_stage', models.CharField(choices=[('applicant', 'Applicant'), ('screening', 'Screening'), ('onboarded', 'Onboarded'), ('incubating', 'Incubating'), ('graduated', 'Graduated'), ('exited', 'Exited'), ('declined', 'Declined')], max_length=12)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_changes', to='incubator.enterprise')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_start_year', models.PositiveIntegerField(help_text='2026 means FY 2026/27')),
                ('quarter', models.PositiveSmallIntegerField(help_text='Q1 = Apr-Jun', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Turnover for the quarter')),
                ('permanent_jobs', models.PositiveIntegerField(default=0)),
                ('temporary_jobs', models.PositiveIntegerField(default=0)),
                ('new_jobs', models.PositiveIntegerField(default=0, verbose_name='Jobs created this quarter')),
                ('notes', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incubator.enterprise')),
            ],
            options={
                'ordering': ['-fy_start_year', '-quarter'],
                'constraints': [models.UniqueConstraint(fields=('enterprise', 'fy_start_year', 'quarter'), name='one_report_per_enterprise_quarter')],
            },
        ),
    ]
