# Generated by Django 5.2.17 on 2026-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="competitive_edge",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="customers_market",
            field=models.TextField(blank=True, verbose_name="Customers and market"),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="goals_challenge",
            field=models.TextField(
                blank=True, verbose_name="Goals and stated challenge"
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="jobs_target",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Jobs the enterprise projects, where it quantified one. A projection, never counted as a job created.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="material_readiness",
            field=models.CharField(
                choices=[
                    ("current", "Current and complete"),
                    ("updating", "Needs updating"),
                    ("improvement", "Needs major improvement"),
                    ("registration", "Registration documents only"),
                    ("none", "None"),
                    ("not_captured", "Not captured"),
                ],
                default="not_captured",
                max_length=14,
                verbose_name="Material at intake",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="products_services",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="readiness_tier",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Tier 1 - Growth-ready"),
                    (2, "Tier 2 - Structuring"),
                    (3, "Tier 3 - Foundation"),
                ],
                help_text="Desk-review readiness tier. Guides the type and sequence of support.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("incubatee", "LEEMA Incubatee"),
                    ("reseller", "LEEMA Reseller"),
                    ("strategic", "LEEMA Strategic Partner"),
                    ("tech_applicant", "Technology Incubation applicant"),
                    ("exploring", "Exploring a relationship"),
                ],
                default="exploring",
                help_text="Standing with LEEMA, as reported to SEDFA.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="support_sought",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="target_1_3_years",
            field=models.TextField(blank=True, verbose_name="One to three year target"),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="province",
            field=models.CharField(
                choices=[
                    ("NW", "North West"),
                    ("GP", "Gauteng"),
                    ("NC", "Northern Cape"),
                    ("MP", "Mpumalanga"),
                    ("OT", "Other"),
                    ("XX", "Not stated"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="sector",
            field=models.CharField(
                choices=[
                    ("manufacturing", "Manufacturing"),
                    ("electronics", "Electronics & devices"),
                    ("agro", "Agro-processing"),
                    ("construction", "Construction"),
                    ("ict", "ICT & digital"),
                    ("services", "Services"),
                    ("retail", "Retail & trade"),
                    ("energy", "Energy & automotive"),
                    ("supply", "PPE & general supply"),
                    ("security", "Security"),
                    ("hospitality", "Food & hospitality"),
                    ("electrical", "Electrical"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
