# Generated by Django 5.2.17 on 2026-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubator", "0002_enterprise_competitive_edge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="annual_turnover_at_intake",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Left empty where intake did not capture it. Empty is not zero.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="employees_at_intake",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Left empty where intake did not capture it. Empty is not zero.",
                null=True,
            ),
        ),
    ]
