# Generated by Django 5.2.17 on 2026-09-19 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubator", "0003_alter_enterprise_annual_turnover_at_intake_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="black_owned_pct",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Black-owned %",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="women_owned_pct",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Women-owned %",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="youth_owned_pct",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Youth-owned %",
            ),
        ),
    ]
