# Generated by Django 5.2.17 on 2026-09-19 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubator", "0004_alter_enterprise_black_owned_pct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Linkage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("rationale", models.TextField()),
                ("expected_output", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("introduced", "Introduced"),
                            ("agreed", "Agreement signed"),
                            ("trading", "Trading"),
                            ("lapsed", "Lapsed"),
                        ],
                        default="proposed",
                        max_length=10,
                    ),
                ),
                (
                    "opened_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "providers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Enterprises supplying into this linkage.",
                        related_name="linkages_supplying",
                        to="incubator.enterprise",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Enterprises buying or receiving.",
                        related_name="linkages_receiving",
                        to="incubator.enterprise",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Workstream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("detail", models.TextField(blank=True)),
                (
                    "covers_whole_portfolio",
                    models.BooleanField(
                        default=False,
                        help_text="Tick where the plan says 'all', rather than listing each enterprise.",
                    ),
                ),
                ("start_week", models.PositiveSmallIntegerField()),
                ("end_week", models.PositiveSmallIntegerField()),
                ("deliverable", models.TextField(verbose_name="Deliverable or KPI")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("running", "Running"),
                            ("done", "Complete"),
                            ("blocked", "Blocked"),
                        ],
                        default="planned",
                        max_length=8,
                    ),
                ),
                (
                    "enterprises",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workstreams",
                        to="incubator.enterprise",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cipc", "CIPC registration"),
                            ("tax", "SARS tax compliance"),
                            ("csd", "Central Supplier Database"),
                            ("bbbee", "B-BBEE credentials"),
                            ("bank", "Bank confirmation"),
                            ("popia", "POPIA consent"),
                            ("baseline", "Baseline jobs and turnover"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "Outstanding"),
                            ("requested", "Requested"),
                            ("verified", "Verified"),
                            ("failed", "Not compliant"),
                            ("na", "Not applicable"),
                        ],
                        default="outstanding",
                        max_length=12,
                    ),
                ),
                ("verified_on", models.DateField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Certificate or reference number.",
                        max_length=120,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance",
                        to="incubator.enterprise",
                    ),
                ),
            ],
            options={
                "ordering": ["enterprise__name", "kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enterprise", "kind"), name="one_check_per_kind"
                    )
                ],
            },
        ),
    ]
